# Generated by Django 5.0.6 on 2024-06-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navapp', '0002_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='c_phone',
            field=models.IntegerField(),
        ),
    ]
